name: Sync Notion Types

on:
  schedule:
    - cron: '0 12 * * 5' # weekly on friday at 12:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: '24'

jobs:
  sync-notion-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run sync script
        run: .github/scripts/sync-notion-types.sh
